network:
  routers:
    - name: router1
      ip_address: 192.168.1.1
      interfaces:
        - name: eth0
          ip_address: 192.168.1.1
          netmask: 255.255.255.0
          connected_devices:
            - name: PC1
              ip_address: 192.168.1.2
            - name: Printer1
              ip_address: 192.168.1.3
        - name: eth1
          ip_address: 10.0.0.1
          netmask: 255.255.255.0
          connected_devices:
            - name: Laptop1
              ip_address: 10.0.0.2
    - name: router2
      ip_address: 192.168.2.1
      interfaces:
        - name: eth0
          ip_address: 192.168.2.1
          netmask: 255.255.255.0
          connected_devices:
            - name: PC2
              ip_address: 192.168.2.2
            - name: Printer2
              ip_address: 192.168.2.3
  devices:
    - name: PC3
      ip_address: 192.168.1.4
    - name: Laptop2
      ip_address: 10.0.0.3
