import time
from t9_1_logger import Logger

logger_1 = Logger()  # Generates file with name 2024-05-18-04-32.log

logger_1.show_log_banner("Hello Joe!")
logger_1.show_log_header("Good Bye Joe!")

logger_1.log_banner("Hello R2D2!")
logger_1.log_header("Goodbye R2D2!'")

logger_1.show_log_init("This initialization message is generated by "\
                       "show_log_init method")
logger_1.show_log_action("This action message is generated by "\
                         "show_log_action method")
logger_1.show_log_warning("This warning message is generated by "\
                          "show_log_warning method")
logger_1.show_log_alert("This alert message is generated by "\
                        "show_log_alert method")
logger_1.show_log_info("This info message is generated by "\
                       "show_log_info method")
time.sleep(2)
logger_1.log_init("This initialization message is generated by "\
                  "log_init method")
logger_1.log_action("This action message is generated by "\
                    "log_action method")
logger_1.log_warning("This warning message is generated by "\
                     "log_warning method")
logger_1.log_alert("This alert message is generated by "\
                   "log_alert method")
logger_1.log_info("This info message is generated by "\
                  "log_info method")
logger_1.report()
print()
logger_2 = Logger('my_logfile.log')  # Generates file with name my_logfile.log
logger_2.log_info("This info message is generated by "\
                  "log_info method")
logger_2.report()
