LOGIN_PAGE_URL = "https://www.saucedemo.com/v1/"
ENTER_USERNAME_XPATH = "//input[@data-test='username']"
ENTER_PASSWORD = "//input[@data-test='password']"
CLICK_LOGIN = "//input[@value='LOGIN']"
ERROR_MESSAGE = "//h3[@data-test='error']"
